### ISSUE TITLE
Should you add a try catch here if the open call fails?

### ISSUE THREAD

**Issue by ousamabenyounes** [sfinx13/fundraising-webscrapper#1]
https://github.com/sfinx13/fundraising-webscrapper/blob/fb2a88e751c47b50f4e279f1f1b8c30f7a834795/utils.py#L34

Thank for advance @sfinx13

**Comment by sfinx13** [comment]
Thanks for the feedback, good notice cause `open` function raises `OSError`  

For simplicity I have just handle it with adding `try...except Exception` on the main function and `OSError` inherits from `Exception`

https://github.com/sfinx13/fundraising-webscrapper/blob/81328f3e48324392ff2e8de6a083d646d6889328/app.py#L19
